### ISSUE TITLE
Paralimypic sport page

### ISSUE THREAD

**Issue by perses76** [SocialHackersClass9/D4DApp#31]
Create paralympic sports page from Docx file (from the client).

**Comment by Evina88** [comment]
Changes to be made:
1. Leave some more space between the PARALYMPIC SPORTS title and the image
2. History of Paralympic Sports should be without any quotes("") and all in the same line and size
3. The history doesn't need to be hidden, Display it all, copy-paste

> The Paralympic Games (ParalympicGames) are the corresponding Olympic Games for athletes with motor, visual or mental disabilities.

The first races for athletes with disabilities took place in 1948 in StokeMadville, England. On the day of the opening ceremony for the 1948 Olympic Games in London, the StokeMadeville Games began and were instituted and the first wheelchair sports event took place.
Four years later, athletes from the Netherlands took part in these games, giving birth to the international movement now known as the Paralympic Movement.
The first Olympic Games for athletes with disabilities were organized in 1960 in Rome, after the Olympic Games in the same city. They are considered to be the first Paralympic Games. About 400 athletes from 23 countries participated in 8 sports, 6 of which are still included in the program of the Paralympic Games (Archery, Swimming, Fencing, Basketball, Table Tennis, Athletics).
Since then, the Paralympic Games are held every 4 years, always in the same year as the Olympic Games. In 1976 in Toronto, other categories of disability were added and the idea of ​​merging different categories of athletes with disabilities for their participation in international sporting events was born. The same year saw the first Winter Paralympic Games in Sweden.
The Seoul Paralympic Games (1988) also stood out from the fact that the Olympic and Paralympic Games were hosted in the same country, in the same city and the same facilities as the Olympic Games were used. Since then, the Paralympic Games have always been held in the same city as the Olympic Games.
Since 1960, twelve (12) Summer Paralympic Games and nine (9) Winter Games have been organized. The Paralympic Games have now become the second largest sporting event after the Olympics.

Greek athletes have been participating in the Paralympic Games since 1976. Since 1988, Greece has been participating in the Games with official National Missions. All these years, the Greek athletes achieved good performance and won many medals.
The first participation of a Greek Athlete in the Winter Paralympic Games took place in 2002 in Salt Lake City. The Torino Paralympic Games in 2006 were the second Winter Paralympic Games in which a Greek Mission participated. The Vancouver Paralympic Winter Games are the third Winter Games that Greece will participate with the participation of the first athlete.<

**Comment by Evina88** [comment]
4. SUMMER needs to be changed to SUMMER PARALYMPIC SPORTS
5. After the title, copy-paste this text: 
> The competition program of the Summer Paralympic Games now includes 22 summer sports. Eighteen of them are common to the Olympics and the other four are exclusively Paralympic. These are Botsia, Golf, Weightlifting and Wheelchair Rugby. The sport of 5x5 Football was added to the Athens Games, while in Beijing for the first time athletes competed in Rowing. Canoe and Triathlon were added to the Rio Games.
The records set at the Paralympic Games can be compared to the records of the Olympic athletes (such as in the men's 100m in Track and Field) and in some cases (such as in weightlifting) the Paralympic records surpass those of athletes without disabilities.
In some sports athletes from all or most categories of disability participate, while in others from only one category.
In detail, the Paralympic sports are:<

**Comment by Evina88** [comment]
After this comes a list with all the summer paralympic sports. I believe you should not use 2 columns, just one. 
What you should do is create an ordered list as in the doc file. 
The name of the sports should be visible. (ex. 1)Αντισφαίριση με αμαξίδιο =>which translates to 1) Wheelchair tennis)
Use google translate for that.
The text after it should be hidden and displayed only if user presses on the name of the sport. So the p that starts with 'Η Αντισφαίριση με αμαξίδιο είναι ...' should be hidden originally. 

I hope that makes sense. If you can make the changes up to 5, I will help you with all the rest and explain anything tomorrow

**Comment by murtazahassani69** [comment]
Evina thank you for your feedback!
all make sense just about the last one I don't understand exactly! 

((ex. 1)Αντισφαίριση με αμαξίδιο) this should be the title of lists right? 
and it should be in one column, right?
what text should I write in the details, if user press on the (ex. 1)Αντισφαίριση με αμαξίδιο?

:)

**Comment by Evina88** [comment]
The title is Summer Paralympic Sports. The first item is 1)Αντισφαίριση με αμαξίδιο, the second 2)Άρση βαρών σε πάγκο and so on. The small text they have under them is the hidden text that should appear on click. For the 1st one is the p after the title (Η Αντισφαίριση με αμαξίδιο είναι ένα δυναμικό άθλημα και έχει...). Do you want to pass the texts through Google translate and send it to you?

**Comment by murtazahassani69** [comment]
Ohh ok!
thanks no need to translate!
:)

**Comment by Evina88** [comment]
Pending correction if needed.
